pub mod term;
pub mod sentence;
pub mod truth;
pub mod unify;
pub mod memory;
pub mod rules;
pub mod control;
pub mod parser;
pub mod static_rules;
pub mod glove;
pub mod bag;
mod tests;
mod tests_integration;
